@echo off

git config --global alias.bdiff "difftool --dir-diff --no-symlinks"
git config --global alias.restore "checkout --"
git config --global alias.restoreall "reset --hard"
git config --global alias.alias "config --get-regexp alias"
git config --global alias.updateremotes "remote update origin --prune"
git config --global alias.unstage "reset HEAD"
git config --global alias.incoming "!python $COMMAND_UTILITIES_PATH\\src\\git_incoming.py"
git config --global alias.outgoing "!python $COMMAND_UTILITIES_PATH\\src\\git_outgoing.py"
git config --global alias.in "incoming"
git config --global alias.out "outgoing"
git config --global alias.contains "branch --contains"
git config --global alias.cleanall "clean -Xfd"
git config --global alias.undolastcommit "reset --soft HEAD~1"
git config --global alias.accepttheirs "checkout --theirs --"
git config --global alias.acceptours "checkout --ours --"
git config --global alias.resolveconflicts "mergetool"
git config --global alias.resolve "resolveconflicts"
git config --global alias.showbase "!python $COMMAND_UTILITIES_PATH\\src\\git_show_rev.py :1"
git config --global alias.showours "!python $COMMAND_UTILITIES_PATH\\src\\git_show_rev.py :2"
git config --global alias.showtheirs "!python $COMMAND_UTILITIES_PATH\\src\\git_show_rev.py :3"
git config --global alias.showchangedfiles "!python $COMMAND_UTILITIES_PATH\\src\\git_files_changed_between_revs.py"
git config --global alias.accepttheirsonfilesthathavenotchanged "!python $COMMAND_UTILITIES_PATH\\src\\git_accept_theirs_on_files_that_have_not_changed.py"